---
dependencies: []

galaxy_info:
  author: Xavier
  description: Nexus Repository Manager role for TP2026
  company: HESIAS
  license: MIT
  min_ansible_version: "2.9"

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - buster
        - bullseye

  galaxy_tags:
    - nexus
    - repository
    - maven
    - docker
    - npm
