---
- name: Validate haproxy configuration
  ansible.builtin.command:
    cmd: haproxy -c -f {{ haproxy_config_file }}
  changed_when: false
  become: true

- name: Restart haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted
  become: true

- name: Reload haproxy
  ansible.builtin.service:
    name: haproxy
    state: reloaded
  become: true
